config/routes.rb
Turnos::Application.routes.draw do
  #root "pages#home"
  #get "home", to: "pages#home", as: "home"
  #get "inside", to: "pages#inside", as: "inside"


  devise_for :users

  root "base#index"
  resources :users
  resources :events
  resources :resources
  resources :resource_types

  namespace :api do
    namespace :v1 do
      resources :events
      put "events/update", to: "events#update"
      delete "events/destroy", to: "events#destroy"
    end
  end
end

app/controllers/resource_types_controller.rb
class ResourceTypesController < BaseController
  before_action :find_resource_type, except: [:index, :new, :create]

  def index
    @resource_types = ResourceType.all.page params[:page]
  end

  def show
  end

  def new
    @resource_type = ResourceType.new
  end

  def edit
  end

  def create
    @resource_type = ResourceType.new(params[:resource_type])
    if @resource_type.save
      flash[:notice] = 'ResourceType successfully created'
      redirect_to admin_resource_types_path
    else
      flash[:error] = 'Something went wrong'
      render 'new'
    end
  end

  def update
    if @resource_type.update_attributes(params[:resource_type])
      flash[:notice] = 'ResourceType was successfully updated'
      redirect_to admin_resource_types_path
    else
      flash[:error] = 'Something went wrong'
      render 'edit'
    end
  end

  def destroy
    if @resource_type.destroy
      flash[:notice] = 'ResourceType was successfully deleted'
      redirect_to admin_resource_types_path
    else
      flash[:error] = 'Something went wrong'
      redirect_to admin_resource_types_path
    end
  end

  private

  def find_resource_type
    @resource_type = ResourceType.find(params[:id])
  end

end

app/views/resource_types/_form.html.erb
<%= simple_form_for [:admin,@resource_type] do |f| %>
  <div class="box-body">
    <%= f.input :title %>
    <%= f.input :multiple %>
    <%= f.input :field %>

  </div>

  <div class="box-footer">
    <%= f.submit "Enviar", :class => "btn btn-primary" %>
  </div>
<% end %>

app/views/resource_types/edit.html.erb
<div class="row">
  <div class="col-lg-3 col-xs-6">
      <!-- small box -->
      <div class="small-box bg-teal">
          <div class="inner">
              <h3>
                  <%= @resource_type.resources.count %>
              </h3>
              <p>
                  Recursos(s) utilizando<br/> este recurso
              </p>
          </div>
          <div class="icon">
              <i class="ion ion-ios7-alarm-outline"></i>
          </div>
          <div class="small-box-footer"></div>
      </div>
  </div>
</div>
<div class="row">
  <div class="col-md-12">
    <div class="box">
      <div class="box-header">
        <h3 class="box-title">Editar Tipo de Recurso</h3>

      </div>
      <%= render "form" %>
    </div>
  </div>
</div>

app/views/resource_types/index.html.erb
<div class="row">
  <div class="col-md-6">
    <div class="box">
      <div class="box-header">
        <h3 class="box-title">Administre los Tipos de Recursos</h3>
        <div class="pull-right box-tools">
          <a href="<%= new_resource_path %>" class="btn btn-default">Nuevo Tipo de Recurso</a>
        </div>
      </div>
      <div class="box-body table-responsive no-padding">
        <div class="text-center">
          <%= paginate @resource_types %>
        </div>
        <table class="table table-hover">
          <tbody>
            <tr>
              <th>ID</th>
              <th>Nombre</th>
              <th>Multiples</th>
              <th>Campo</th>
              <th></th>
            </tr>
            <% @resource_types.each do |rt| %>
            <tr>
              <td><%= rt.id %></td>
              <td><%= rt.title %></td>
              <td><%= t rt.multiple.to_s %> </td>
              <td><%= rt.field %></td>
              <td>
                <div class="btn-group">
                    <a href="<%= edit_resource_type_path(rt)%>" type="button" class="btn btn-default">Editar</a>
                    <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
                        <span class="caret"></span>
                        <span class="sr-only">Ver Mas</span>
                    </button>
                    <ul class="dropdown-menu" role="menu">
                        <li><a href="<%= resource_type_path(rt) %>" data-method="delete" data-confirm="Esta seguro?">Eliminar</a></li>
                    </ul>
                </div>
              </td>
            </tr>

            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>