config/routes.rb
Turnos::Application.routes.draw do
  #root "pages#home"
  #get "home", to: "pages#home", as: "home"
  #get "inside", to: "pages#inside", as: "inside"


  devise_for :users

  root "base#index"
  resources :users
  resources :events
  resources :resources
  resources :resource_types

  namespace :api do
    namespace :v1 do
      resources :events
      put "events/update", to: "events#update"
      delete "events/destroy", to: "events#destroy"
    end
  end
end

app/models/event.rb
class Event < ActiveRecord::Base
  attr_accessible :title, :start, :end, :startTimezone, :endTimezone, :description, :recurrenceId, :recurrenceRule, :recurrenceException, :isAllDay
  has_and_belongs_to_many :resources

  scope :next_events, -> (number_of_events = nil) {
    where("start > ?", DateTime.now).order("start ASC").limit(number_of_events)
  }
  def assign_resources(event_params)
    types = ResourceType.all.map {|m| m.multiple? ? m.title : m.field}
    types.each do |type|

      resources = self.resources.includes(:resource_type).where("resource_types.title = ? OR resource_types.field = ? ", type, type).references(:resource_type)
      resource_ids = resources.map {|r| r.id}
      ids = (event_params[type].is_a? Array) ? event_params[type].map {|a| a.to_i} : event_params[type].to_i


      # checks if related resources matches resources given by POST request
      if !resource_ids.empty? && (resource_ids != ids)
        self.resources.destroy resources
      end


      # if given resources are the same... don't do anything
      unless resource_ids == ids
        unless ids == 0
          if ids.is_a? Integer
            self.resources << Resource.find(ids)
          else
            ids.each do |id|
              self.resources << Resource.find(id)
            end
          end
        end
      end

    end
  end
end

app/controllers/api/v1/events_controller.rb
module Api
  module V1
    class EventsController < ApplicationController
      respond_to :json
      def index
        @events = Event.includes(:resources)
      end

      def show
        @event = Event.find(params[:id])
      end

      def update
        event_params = params[:models]["0"]

        if event_params[:id].present?
          @event = Event.find(event_params[:id])
          @event.title = event_params[:title]
          @event.start = event_params[:start]
          @event.end = event_params[:end]
          @event.startTimezone = event_params[:startTimezone]
          @event.endTimezone = event_params[:endTimezone]
          @event.description = event_params[:description]
          @event.recurrenceId = event_params[:recurrenceId]
          @event.recurrenceRule = event_params[:recurrenceRule]
          @event.recurrenceException = event_params[:recurrenceException]
          @event.isAllDay = event_params[:isAllDay]
          if @event.save
            @event.assign_resources(event_params)
          end
          Rabl.render(@event, 'events/show', :view_path => 'app/views/api/v1', :format => :json)
        end
      end

      def create
        event_params = params[:models]["0"]
        @event = Event.new(event_params)
        if @event.save
          @event.assign_resources(event_params)
          Rabl.render(@event, 'events/show', :view_path => 'app/views/api/v1', :format => :json)
        end
      end

      def destroy
        @event = Event.find(params[:models]["0"][:id])
        @event.destroy
        Rabl.render(@event, 'events/show', :view_path => 'app/views/api/v1', :format => :json)
      end

    end
  end
end

app/controllers/events_controller.rb
class EventsController < BaseController
  def index
    #@events = Event.all
  end
end

app/views/events/_index.js.erb
$(function() {
    kendo.culture('es');
    $("#scheduler").kendoScheduler({
        height: 600,
        views: [
            "day",
            "week",
            { type: "month", selected: true },
            "agenda"
        ],
        timezone: "Etc/UTC",
        dataSource: {
            batch: true,
            transport: {
                read: {
                    url: "<%= api_v1_events_path %>.json",
                    dataType: "jsonp"
                },
                update: {
                    url: "<%= api_v1_events_path %>/update",
                    dataType: "jsonp",
                    type: 'PUT'
                },
                create: {
                    url: "<%= api_v1_events_path %>",
                    dataType: "jsonp",
                    type: 'POST'
                },
                destroy: {
                    url: "<%= api_v1_events_path %>/destroy",
                    dataType: "jsonp",
                    type: 'DELETE'
                }
            },
            schema: {
                model: {
                    id: "id",
                    fields: {
                        id: { from: "id", type: "number" },
                        title: { from: "title", defaultValue: "", validation: { required: true } },
                        start: { type: "date", from: "start" },
                        end: { type: "date", from: "end" },
                        startTimezone: { from: "startTimezone" },
                        endTimezone: { from: "endTimezone" },
                        description: { from: "description" },
                        recurrenceId: { from: "recurrenceId" },
                        recurrenceRule: { from: "recurrenceRule" },
                        recurrenceException: { from: "recurrenceException" },
                        isAllDay: { type: "boolean", from: "isAllDay" },
                        <%= resource_type_fields.html_safe %>
                    }
                }
            }
        },
        resources: <%= print_resources.html_safe %>,
        editable: {
            confirmation: "Esta seguro de eliminar este turno?"
          },
        messages: {
            views: {
                day: "Dia",
                week: "Semana",
                month: "Mes"
            },
            editor: {
               editorTitle: "Editar turno",
               title: "Titulo",
               start: "Inicio",
               end: "Fin",
               allDayEvent: "Todo el dia",
               repeat: "Repetir",
               description: "Descripcion"
            },
            recurrenceEditor: {
                frequencies: {
                    daily: "Diariamente",
                    monthly: "Mensualmente",
                    never: "Nunca",
                    weekly: "Semanalmente",
                    yearly: "Anualmente"
                },
                daily: {
                    repeatEvery: "Repetir cada: ",
                    interval: " dia(s)"
                },
                weekly: {
                    repeatEvery: "Repetir cada: ",
                    interval: " dia(s)"
                },
                end: {
                    never: " Nunca",
                    after: " Después de ",
                    occurrence: " ocurrencias(s).",
                    on: " En"
                }
            },
            event: "Turno",
            today: "Hoy",
            save: "Guardar",
            cancel: "Cancelar",
            destroy: "Eliminar",
            deleteWindowTitle: "Eliminar turno"
        }
    });
/*
    $("#people :checkbox").change(function(e) {
        var checked = $.map($("#people :checked"), function(checkbox) {
            return parseInt($(checkbox).val());
        });

        var scheduler = $("#scheduler").data("kendoScheduler");

        scheduler.dataSource.filter({
            operator: function(task) {
                return $.inArray(task.ownerId, checked) >= 0;
            }
        });
    });
*/
});

app/views/events/index.html.erb
<% content_for :footer do %>
<script type="text/javascript">
    <%= render 'events/index.js' %>
</script>
<% end %>

        <!--
        <h3 class="box-title">Administre sus tareas</h3>
        <div class="pull-right box-tools">
          <div class="btn-group">
            <button class="btn btn-default dropdown-toggle" data-toggle="dropdown">
              Configurar <span class="caret"></span>
            </button>
            <ul class="dropdown-menu pull-right" role="menu">
              <li><a href="<%= resources_path %>">Recursos</a></li>
              <li><a href="<%= resource_types_path %>">Tipos de Recursos</a></li>
            </ul>
          </div>
-->
          <!--<a href="<%= resources_path %>" class="btn btn-primary btn-sm daterange pull-right" data-toggle="tooltip" title="" data-original-title="Editar Recursos" style="color: white"><i class="fa fa-calendar"></i></a>-->

<div id="scheduler"></div>