config/routes.rb
Turnos::Application.routes.draw do
  #root "pages#home"
  #get "home", to: "pages#home", as: "home"
  #get "inside", to: "pages#inside", as: "inside"


  devise_for :users

  root "base#index"
  resources :users
  resources :events
  resources :resources
  resources :resource_types

  namespace :api do
    namespace :v1 do
      resources :events
      put "events/update", to: "events#update"
      delete "events/destroy", to: "events#destroy"
    end
  end
end

app/views/resources/_form.html.erb
<%= simple_form_for [:admin,@resource] do |f| %>
  <div class="box-body">
    <%= f.input :text %>
    <%= f.input :color, :input_html => {:class => "colorpicker-element my-colorpicker1"} %>
    <%= f.association :resource_type, include_blank: "Seleccione un Tipo" %>
  </div>

  <div class="box-footer">
    <%= f.submit "Enviar", :class => "btn btn-primary" %>
  </div>
<% end %>

app/views/resources/edit.html.erb
<div class="row">
  <div class="col-lg-3 col-xs-6">
      <!-- small box -->
      <div class="small-box bg-teal">
          <div class="inner">
              <h3>
                  <%= @resource.events.count %>
              </h3>
              <p>
                  Evento(s) utilizando<br/> este recurso
              </p>
          </div>
          <div class="icon">
              <i class="ion ion-ios7-alarm-outline"></i>
          </div>
          <div class="small-box-footer"></div>
      </div>
  </div>
</div>
<div class="row">
  <div class="col-md-12">
    <div class="box">
      <div class="box-header">
        <h3 class="box-title">Editar Recurso</h3>

      </div>
      <%= render "form" %>
    </div>
  </div>
</div>

app/views/resources/index.html.erb
<div class="row">
  <div class="col-md-6">
    <div class="box">
      <div class="box-header">
        <h3 class="box-title">Administre los Recursos del Calendario</h3>
        <div class="pull-right box-tools">
          <a href="<%= new_resource_path %>" class="btn btn-default">Nuevo Recurso</a>
        </div>
      </div>
      <div class="box-body table-responsive no-padding">
        <div class="text-center">
          <%= paginate @resources %>
        </div>
        <table class="table table-hover">
          <tbody>
            <tr>
              <th>ID</th>
              <th>Nombre</th>
              <th>Color</th>
              <th></th>
            </tr>
            <% @resources.each do |r| %>
            <tr>
              <td><%= r.id %></td>
              <td><%= r.text %></td>
              <td><span class="label" style="background-color:<%= r.color %>;">&nbsp;</span> <%= r.color %> </td>
              <td>
                <div class="btn-group">
                    <a href="<%= edit_resource_path(r)%>" type="button" class="btn btn-default">Editar</a>
                    <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
                        <span class="caret"></span>
                        <span class="sr-only">Ver Mas</span>
                    </button>
                    <ul class="dropdown-menu" role="menu">
                        <li><a href="<%= resource_path(r) %>" data-method="delete" data-confirm="Esta seguro?">Eliminar</a></li>
                    </ul>
                </div>
              </td>
            </tr>

            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/resources/new.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="box">
      <div class="box-header">
        <h3 class="box-title">Nuevo Recurso</h3>

      </div>
      <%= render "form" %>
    </div>
  </div>
</div>